### ISSUE TITLE
Page 89 broken plot

### ISSUE THREAD

**Issue by Deleetdk** [Derek-Jones/ESEUR-code-data#1]
![Screenshot from 2020-05-18 21-30-07](https://user-images.githubusercontent.com/6759913/82252164-c92eae80-994e-11ea-9ee0-952cce02cbb9.png)

**Comment by Derek-Jones** [comment]
Ah, the joys of the sidenote package in LaTeX.

On the basis that things are going to shuffle around again, I let this one slip through.

**Comment by Deleetdk** [comment]
Same issue on p. 123

![Screenshot from 2020-05-19 14-29-01](https://user-images.githubusercontent.com/6759913/82326441-1fe2c980-99dd-11ea-997a-457e95c1c8c0.png)

**Comment by Deleetdk** [comment]
![Screenshot from 2020-05-19 15-27-39](https://user-images.githubusercontent.com/6759913/82332115-4b69b200-99e5-11ea-81a9-50771d877789.png)

**Comment by Derek-Jones** [comment]
Yes, this species diversity plot looks horrible (and it was done using `ggplot2` ;-).

Readers are assumed to be casual users of statistics.  So when coding I try to follow the pipeline readData -> callAppropriateFunction -> plotResults

Sometimes the package authors plotResults function produces what you see (it took me a while to find the option settings that improved on the default, which was a lot worse).

**Comment by Deleetdk** [comment]
![Screenshot from 2020-05-19 17-05-23](https://user-images.githubusercontent.com/6759913/82343291-f2087f80-99f2-11ea-8b29-424736b44ef1.png)

**Comment by Derek-Jones** [comment]
All fixed.
