### ISSUE TITLE
mobi format for reviewers

### ISSUE THREAD

**Issue by henricook** [Derek-Jones/ESEUR-code-data#13]
I'd love to have a read of this on Kindle, PDF doesn't perform very well there. Might you consider a .mobi or .epub?

**Comment by Derek-Jones** [comment]
[Asciidoc](http://asciidoc.org/) is used as the document preparation system, so in theory generating something other than pdf should be easy.  In practice [various scripts are used to transform the material](https://shape-of-code.coding-guidelines.com/2019/08/11/my-books-pdf-generation-workflow/) before it is finally processed by [LuaLaTex](https://en.wikipedia.org/wiki/LaTeX) to produce a pdf, i.e., generating some form of html will need some work.

It is possible to generate just the figures in a html friendly way (at least it was until I started adding math formula to the captions).

Might a figures only version be useful as a way of searching for something of interest?

**Comment by henricook** [comment]
Fair enough! Thanks for triaging this for me. I don't think you need to spend your valuable time on a figures only version, the whole book was the goal of my post but I understand the technical constraints as you've explained them. Thanks
