### ISSUE TITLE
Page 83, plot axis issue

### ISSUE THREAD

**Issue by Deleetdk** [Derek-Jones/ESEUR-code-data#2]
![Screenshot from 2020-05-18 21-31-15](https://user-images.githubusercontent.com/6759913/82252227-ee232180-994e-11ea-97da-2bb836d02be5.png)

**Comment by Derek-Jones** [comment]
R has no option to print scientific (i.e., power of 10) labels.  The `magicaxis` package adds this support, but I want plots to be as 'standard' as possible.

Might add an extra '\n"' to the label to move the label out a bit.

A work in progress.

**Comment by Derek-Jones** [comment]
Fixed.
