### ISSUE TITLE
Page 92, legend on top of data

### ISSUE THREAD

**Issue by Deleetdk** [Derek-Jones/ESEUR-code-data#3]
Slightly hard to read, should probably make a big more whitespace upwards.

![Screenshot from 2020-05-18 21-36-16](https://user-images.githubusercontent.com/6759913/82252643-aa7ce780-994f-11ea-843f-dd5027e721f8.png)

**Comment by Derek-Jones** [comment]
I have shuffled the legend around a bit, shrinking it helps, or maybe put it on the right.

Plots in the software engineering material are a work in progress.

**Comment by Deleetdk** [comment]
Why don't you just use ggplot2? Much easier than base R plot, IMO.

**Comment by Derek-Jones** [comment]
The code is intended to be understood by casual users of R.

People tell me that `ggplot2` can be learned in half a day, but that is half a day the average developer does not want to spend learning another plotting package.

**Comment by Deleetdk** [comment]
Your argument makes little sense. More novice coders know **ggplot2** than base plot these days (because everybody teachers **tidyverse**, and rightfully so IMO). Besides, you know perfectly well that very very few people actually read your code, and in any case, your code is mostly uncommented from my skimming of a few files, hence would be unsuitable for novices in any case. I can understand that you don't want to spend the effort to convert the plots, but these errors would be a lot easier to avoid in **ggplot2**. :)

**Comment by Derek-Jones** [comment]
I don't know about novices, but most experienced developers don't know any R at all.  In 5-years time this may have changed.

I don't know how many people read the code (as you say, not a lot), but using ggplot will introduce friction.

The book is aimed at professional developers, it is too advanced for novices.

I have been slowly adding comments, as I fix up the plots.  As always, more would be better.

**Comment by Derek-Jones** [comment]
Fixed.
