### ISSUE TITLE
Page 105, unreadable axis text

### ISSUE THREAD

**Issue by Deleetdk** [Derek-Jones/ESEUR-code-data#4]
![Screenshot from 2020-05-18 21-51-23](https://user-images.githubusercontent.com/6759913/82253683-bff31100-9951-11ea-8428-ef100b873d3c.png)

**Comment by Derek-Jones** [comment]
Yes, just spotted that recently.  Hoping that rescaling the axis into MLOC solves the problem.

Thanks for the issue reports, but the first seven chapters are not in beta yet, and I have been letting some of the plot issues slide until now.

**Comment by Derek-Jones** [comment]
Fixed.
