### ISSUE TITLE
Page 114, survival curve probably better

### ISSUE THREAD

**Issue by Deleetdk** [Derek-Jones/ESEUR-code-data#5]
I like these data, but at first I was confused about them. I think they would be more clearly communicated with a survival curve type plot.

![Screenshot from 2020-05-19 13-37-23](https://user-images.githubusercontent.com/6759913/82321953-ff634100-99d5-11ea-8384-7e6e04ad9b98.png)

**Comment by Derek-Jones** [comment]
Done.
