### ISSUE TITLE
Page 122: error in axis label

### ISSUE THREAD

**Issue by Deleetdk** [Derek-Jones/ESEUR-code-data#6]
Seems like there is an error in the Y axis label here. It should be just "Effort" or maybe "Effort (central tendency)". I am guessing you wrote the label, and then later added the medians.

![Screenshot from 2020-05-19 14-26-36](https://user-images.githubusercontent.com/6759913/82326319-e742f000-99dc-11ea-88de-d5aea2c36a12.png)

**Comment by Derek-Jones** [comment]
Removed "mean" from y axis label.

Changed "hours" -> "thousand hours" in caption.

**Comment by Derek-Jones** [comment]
Fixed.
