### ISSUE TITLE
Page 196, overlapping and outside plot text

### ISSUE THREAD

**Issue by Deleetdk** [Derek-Jones/ESEUR-code-data#8]
![Screenshot from 2020-05-19 17-24-52](https://user-images.githubusercontent.com/6759913/82345558-b327f900-99f5-11ea-94d7-7a5861e74b3e.png)

**Comment by Derek-Jones** [comment]
The plot looks ok when run in an R session.  It might be something that is a side-effect of the build process.

My quick scan over the plots before release missed it.  Will specifically check this plot after the next build.

**Comment by Derek-Jones** [comment]
Fixed.
