### ISSUE TITLE
Page 233, slight error in plot

### ISSUE THREAD

**Issue by Deleetdk** [Derek-Jones/ESEUR-code-data#9]
For some reason, there is a slight upwards spike in the pdf for the normal curve on the left tail here.

![Screenshot from 2020-05-22 15-17-37](https://user-images.githubusercontent.com/6759913/82671607-6b94ad80-9c3f-11ea-8214-03ab0eca5b0c.png)

**Comment by Derek-Jones** [comment]
Fixed: the shorter reply.

The first entry for the distribution values returned in `chisqtable`, by `gofstat`, is the cumulative value of everything to the left.  So need to ignore this value.
